### ISSUE TITLE
out of memory allocating heap arena metadata

### ISSUE THREAD

**Issue by zplzpl** [timescale/tsbs#112]
--scale=10000000 --timestamp-start="2019-12-24T00:00:00Z" --timestamp-end="2019-12-31T00:00:00Z"

```
 tsbs_generate_data.exe --use-case="iot" --seed=123 --scale=10000000 --timestamp-start="2019-12-24T00:00:00Z" --timestamp-end="2019-12-31T00:00:00Z" --log-interval="24h" --format="timescaledb" | gzip > testdata1.gz

fatal error: out of memory allocating heap arena metadata

runtime stack:
runtime.throw(0x971029, 0x2c)
        D:/go/1.13/src/runtime/panic.go:774 +0x79
runtime.(*mheap).sysAlloc(0xd3c800, 0x2000, 0x1000, 0x4)
        D:/go/1.13/src/runtime/malloc.go:724 +0x6d8
runtime.(*mheap).grow(0xd3c800, 0x1, 0xffffffff)
        D:/go/1.13/src/runtime/mheap.go:1252 +0x49
runtime.(*mheap).allocSpanLocked(0xd3c800, 0x1, 0xd55428, 0x75b7a150)
        D:/go/1.13/src/runtime/mheap.go:1163 +0x298
runtime.(*mheap).alloc_m(0xd3c800, 0x1, 0x450008, 0x75b7a150)
        D:/go/1.13/src/runtime/mheap.go:1015 +0xd0
runtime.(*mheap).alloc.func1()
        D:/go/1.13/src/runtime/mheap.go:1086 +0x53
runtime.systemstack(0x0)
        D:/go/1.13/src/runtime/asm_amd64.s:370 +0x6b
runtime.mstart()
        D:/go/1.13/src/runtime/proc.go:1146

goroutine 1 [running]:
runtime.systemstack_switch()
        D:/go/1.13/src/runtime/asm_amd64.s:330 fp=0xc461235820 sp=0xc461235818 pc=0x458e20
runtime.(*mheap).alloc(0xd3c800, 0x1, 0x10008, 0x203180f)
        D:/go/1.13/src/runtime/mheap.go:1085 +0x91 fp=0xc461235870 sp=0xc461235820 pc=0x426341
runtime.(*mcentral).grow(0xd3cf98, 0x0)
        D:/go/1.13/src/runtime/mcentral.go:255 +0x82 fp=0xc4612358b0 sp=0xc461235870 pc=0x417dd2
runtime.(*mcentral).cacheSpan(0xd3cf98, 0x203180f)
        D:/go/1.13/src/runtime/mcentral.go:106 +0x305 fp=0xc461235910 sp=0xc4612358b0 pc=0x4178f5
runtime.(*mcache).refill(0x180008, 0x8)
        D:/go/1.13/src/runtime/mcache.go:138 +0x8c fp=0xc461235930 sp=0xc461235910 pc=0x41737c
runtime.(*mcache).nextFree(0x180008, 0x8, 0x10, 0x8c9cc0, 0xc603ff6940)
        D:/go/1.13/src/runtime/malloc.go:854 +0x8e fp=0xc461235968 sp=0xc461235930 pc=0x40ba2e
runtime.mallocgc(0x30, 0x8a6a00, 0x1, 0xc603fd0cd0)
        D:/go/1.13/src/runtime/malloc.go:1022 +0x7d2 fp=0xc461235a08 sp=0xc461235968 pc=0x40c3b2
runtime.growslice(0x8a6a00, 0xc603ff51c0, 0x1, 0x1, 0x2, 0xc603fd0cd0, 0x0, 0x1)
        D:/go/1.13/src/runtime/slice.go:181 +0x1e9 fp=0xc461235a70 sp=0xc461235a08 pc=0x443639
github.com/timescale/tsbs/cmd/tsbs_generate_data/serialize.(*Point).AppendTag(...)
        D:/goproject/src/github.com/timescale/tsbs/cmd/tsbs_generate_data/serialize/point.go:118
github.com/timescale/tsbs/cmd/tsbs_generate_data/common.(*BaseSimulator).Next(0xc407cf6000, 0xc603ff9580, 0x0)
        D:/goproject/src/github.com/timescale/tsbs/cmd/tsbs_generate_data/common/simulator.go:122 +0x452 fp=0xc461235b68 sp=0xc461235a70 pc=0x7f8bc2
github.com/timescale/tsbs/cmd/tsbs_generate_data/iot.(*Simulator).getNextEntry(0xc2f2b34200, 0x5, 0xc603fe5e30, 0xd54000, 0xc603fe5d00)
        D:/goproject/src/github.com/timescale/tsbs/cmd/tsbs_generate_data/iot/simulator.go:235 +0x3a9 fp=0xc461235bf8 sp=0xc461235b68 pc=0x80a579
github.com/timescale/tsbs/cmd/tsbs_generate_data/iot.(*Simulator).generateBatch(0xc2f2b34200, 0xc603fe5e30, 0x7, 0x8, 0xc603fe5e30)
        D:/goproject/src/github.com/timescale/tsbs/cmd/tsbs_generate_data/iot/simulator.go:187 +0xcc fp=0xc461235c50 sp=0xc461235bf8 pc=0x809ffc
github.com/timescale/tsbs/cmd/tsbs_generate_data/iot.(*Simulator).simulateNextBatch(0xc2f2b34200, 0x1)
        D:/goproject/src/github.com/timescale/tsbs/cmd/tsbs_generate_data/iot/simulator.go:164 +0x44e fp=0xc461235d48 sp=0xc461235c50 pc=0x809e3e
github.com/timescale/tsbs/cmd/tsbs_generate_data/iot.(*Simulator).Next(0xc2f2b34200, 0xc2f2b34480, 0xa09020)
        D:/goproject/src/github.com/timescale/tsbs/cmd/tsbs_generate_data/iot/simulator.go:89 +0x262 fp=0xc461235d78 sp=0xc461235d48 pc=0x809992
github.com/timescale/tsbs/internal/inputs.(*DataGenerator).runSimulator(0xd381e0, 0xa148c0, 0xc2f2b34200, 0xa095a0, 0xd532b8, 0xd38420, 0x0, 0x0)
        D:/goproject/src/github.com/timescale/tsbs/internal/inputs/generator_data.go:159 +0x208 fp=0xc461235e50 sp=0xc461235d78 pc=0x85edd8
github.com/timescale/tsbs/internal/inputs.(*DataGenerator).Generate(0xd381e0, 0xa0dfc0, 0xd38420, 0xc0000ac300, 0x95fa63)
        D:/goproject/src/github.com/timescale/tsbs/internal/inputs/generator_data.go:150 +0x181 fp=0xc461235eb8 sp=0xc461235e50 pc=0x85eb61
main.main()
        D:/goproject/src/github.com/timescale/tsbs/cmd/tsbs_generate_data/main.go:65 +0x75 fp=0xc461235f60 sp=0xc461235eb8 pc=0x861015
runtime.main()
        D:/go/1.13/src/runtime/proc.go:203 +0x21e fp=0xc461235fe0 sp=0xc461235f60 pc=0x43255e
runtime.goexit()
        D:/go/1.13/src/runtime/asm_amd64.s:1357 +0x1 fp=0xc461235fe8 sp=0xc461235fe0 pc=0x45ae01

goroutine 6 [syscall, 5 minutes]:
os/signal.signal_recv(0x0)
        D:/go/1.13/src/runtime/sigqueue.go:147 +0xa3
os/signal.loop()
        D:/go/1.13/src/os/signal/signal_unix.go:23 +0x29
created by os/signal.init.0
        D:/go/1.13/src/os/signal/signal_unix.go:29 +0x48

```

**Comment by borisminimoris** [comment]
I got similar problem. 

- OS: Windows 10 64bit
- Memory: 8GB

`ts=2021-12-21T00:33:16.259412Z lvl=info msg="Cache snapshot (start)" log_id=0YWzhsQl000 engine=tsm1 trace_id=0YYbM1sl000 op_name=tsm1_cache_snapshot op_event=start
ts=2021-12-21T00:33:16.941414Z lvl=info msg="Snapshot for path written" log_id=0YWzhsQl000 engine=tsm1 trace_id=0YYbM1sl000 op_name=tsm1_cache_snapshot path=\\Users\\Dewesoft\\.influxdb\\data\\dshqpwra\\autogen\\113623 duration=685.996ms
ts=2021-12-21T00:33:16.943413Z lvl=info msg="Cache snapshot (end)" log_id=0YWzhsQl000 engine=tsm1 trace_id=0YYbM1sl000 op_name=tsm1_cache_snapshot op_event=end op_elapsed=687.995ms
ts=2021-12-21T00:33:34.251459Z lvl=info msg="Cache snapshot (start)" log_id=0YWzhsQl000 engine=tsm1 trace_id=0YYbN8Al000 op_name=tsm1_cache_snapshot op_event=start
fatal error: out of memory allocating heap arena metadata

runtime stack:
runtime.throw(0x16dc1ac, 0x2c)
	/usr/local/go/src/runtime/panic.go:774 +0x79
runtime.(*mheap).sysAlloc(0x35e81c0, 0xe000, 0x4, 0xc70c7f8000)
	/usr/local/go/src/runtime/malloc.go:724 +0x6d8
runtime.(*mheap).grow(0x35e81c0, 0x7, 0xffffffff)
	/usr/local/go/src/runtime/mheap.go:1255 +0xaa
runtime.(*mheap).allocSpanLocked(0x35e81c0, 0x7, 0x3605808, 0x1941e5480)
	/usr/local/go/src/runtime/mheap.go:1170 +0x26d
runtime.(*mheap).alloc_m(0x35e81c0, 0x7, 0x8830067, 0x1941e5480)
	/usr/local/go/src/runtime/mheap.go:1022 +0xd0
runtime.(*mheap).alloc.func1()
	/usr/local/go/src/runtime/mheap.go:1093 +0x53
runtime.systemstack(0x0)
	/usr/local/go/src/runtime/asm_amd64.s:370 +0x6b
runtime.mstart()
	/usr/local/go/src/runtime/proc.go:1146 `
