### ISSUE TITLE
Error while running queries against CrateDB: panic: conn busy 

### ISSUE THREAD

**Issue by seybi87** [timescale/tsbs#201]
Hi TSBS community, 

I am trying to run the `cpu-only` against a CrateDB instance, version `4.7.0`

The data generation and load phase works fine with the following commands:

`/binary/tsbs/bin/tsbs_generate_queries --queries 2000 --query-type single-groupby-1-1-1 --scale 1000 --seed 123 --timestamp-end 2016-01-01T02:00:00Z --use-case cpu-only --format cratedb --file /binary/tsbs/bin/queries`

` /binary/tsbs/bin/tsbs_generate_data --initial-scale 1 --scale 1000 --seed 123 --timestamp-end 2016-01-01T02:00:00Z --use-case cpu-only --format cratedb --file /binary/tsbs/bin/data`

 `/binary/tsbs/bin/tsbs_load_cratedb --hosts 172.31.20.142 --db-name tsbs --user admin --pass topsecret --batch-size 1000 --do-abort-on-exist true --hash-workers false --insert-intervals 1,2 --seed 123 --workers 8 --file /binary/tsbs/bin/data` 
 
 However, if I am trying to run the queries with the following command: 
 
 `/binary/tsbs/bin/tsbs_run_queries_cratedb --hosts 172.31.20.142 --db-name tsbs --user admin --pass topsecret --hdr-latencies hdr --prewarm-queries false --workers 8  --print-interval 100 --file /binary/tsbs/bin/queries`
 
 I get the following error:
 
 `panic: conn busy

goroutine 14 [running]:
github.com/timescale/tsbs/pkg/query.(*BenchmarkRunner).processorHandler(0xc00019a0c0, 0xc00003aef0, 0xc0000a4960, 0xc3f2c0, 0x9ce6d0, 0xc00000e858, 0x7)
        /opt/workloads/tsbs/pkg/mod/github.com/timescale/tsbs@v0.0.0-20220119183622-bcc00137d72d/pkg/query/benchmarker.go:239 +0x28d
created by github.com/timescale/tsbs/pkg/query.(*BenchmarkRunner).Run
        /opt/workloads/tsbs/pkg/mod/github.com/timescale/tsbs@v0.0.0-20220119183622-bcc00137d72d/pkg/query/benchmarker.go:160 +0x206`
        
Any help would be much appreciated

**Comment by seybi87** [comment]
I did a bit of research and it looks like the problem relates to use direct usage of pgx without pgxpool or PgBouncer as decribed here: https://github.com/jackc/pgx/issues/635#issuecomment-629581583

@atanasovskib @kovrus any ideas or comments on  these thoughts?
