### ISSUE TITLE
ERROR: unsupported jsonb version number 123

### ISSUE THREAD

**Issue by UfaSemen** [timescale/tsbs#68]
When executing tsbs_load_timescaledb with data file, generated for devops usecase, it fails with error:
```
panic: ERROR: unsupported jsonb version number 123 (SQLSTATE XX000)

goroutine 27 [running]:
main.(*processor).processCSI(0xc42068ede0, 0xc4200183c0, 0x6, 0xc420adc800, 0x457, 0x500, 0x7757a0)
        /home/semen/work/src/github.com/timescale/tsbs/cmd/tsbs_load_timescaledb/process.go:237 +0xe0c
main.(*processor).ProcessBatch(0xc42068ede0, 0x7f2ec0, 0xc42009ca20, 0x4d2901, 0x1, 0x0)
        /home/semen/work/src/github.com/timescale/tsbs/cmd/tsbs_load_timescaledb/process.go:292 +0x192
github.com/timescale/tsbs/load.(*BenchmarkRunner).work(0x9956e0, 0x7f7fe0, 0x9b26d0, 0xc4200b10b0, 0xc42009c870, 0x0)
        /home/semen/work/src/github.com/timescale/tsbs/load/loader.go:253 +0xc6
created by github.com/timescale/tsbs/load.(*BenchmarkRunner).RunBenchmark
        /home/semen/work/src/github.com/timescale/tsbs/load/loader.go:118 +0x16a
```
Issue is reproduced on Windows and Ubuntu, on Postgre 10, 11.
[datadev.txt](https://github.com/timescale/tsbs/files/3094794/datadev.txt)

**Comment by RobAtticus** [comment]
Thanks for the report, this will be fixed when #69 is merged
